site:
  title: ChannelPointsMiner
  url: https://raksrinana.github.io/ChannelPointsMiner/
  start_page: miner::index.adoc
content:
  sources:
    - url: https://github.com/RakSrinaNa/ChannelPointsMiner.git
      branches: [ doc/antora ]
      start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
runtime:
  fetch: true
  log:
    level: all
output:
  clean: true
  dir: ./antora-docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
