site:
  title: ChannelPointsMiner
  url: https://rakambdaorg.github.io/ChannelPointsMiner/
  start_page: miner::index.adoc
content:
  sources:
    - url: https://github.com/RakambdaOrg/ChannelPointsMiner.git
      branches: [ main, develop ]
      start_paths:
        - miner/docs
        - viewer/docs
asciidoc:
  extensions:
    - asciidoctor-kroki
runtime:
  fetch: true
output:
  clean: true
  dir: ./antora-docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
